[package]
name = "neet_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies", "blocking", "gzip"] }
scraper = "0.15.0"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
